version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.intellij
    versions:
    - 0.6.5
    - 0.7.0
    - 0.7.1
    - 0.7.2
  - dependency-name: junit:junit
    versions:
    - 4.13.1
